version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - depguard
    - err113
    - godot
    - ireturn
    - mnd
    - testpackage
    - varnamelen
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 160
    errorlint:
      asserts: false
    funlen:
      lines: 60
      statements: 40
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - BUG
        - FIXME
    gosec:
      excludes:
        - G402
    interfacebloat:
      max: 15
    nestif:
      min-complexity: 10
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'exported: comment on exported'
      - linters:
          - revive
        text: 'package-comments: package comment should be of the form'
      - linters:
          - staticcheck
        text: 'ST1021: comment on exported type'
      - linters:
          - revive
          - staticcheck
        text: should have a package comment
      - linters:
          - revive
          - staticcheck
        text: should have comment or be unexported
      - linters:
          - revive
          - staticcheck
        text: or a comment on this block
      - linters:
          - gosec
        path: postgres/repo.go
    paths:
      - (\/|^)gen(\/|$)
      - third_party$
      - builtin$
      - examples$
      - (.+)_test.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vasilesk/log)
      custom-order: false
  exclusions:
    generated: lax
    paths:
      - (\/|^)gen(\/|$)
      - third_party$
      - builtin$
      - examples$
      - (.+)_test.go
